export const routes = {
  home: "/",
  projects: "/projects",
  projectCategory: "/projects/category/:category",
  projectDetail: "/projects/:slug",
  blog: "/blog",
  blogCategory: "/blog/category/:category",
  blogTag: "/blog/tag/:tag",
  blogDetail: "/blog/:slug",
  search: "/search",
  contact: "/contact",
  login: "/login",
  admin: {
    dashboard: "/admin",
    profile: "/admin/profile",
    projects: "/admin/projects",
    projectNew: "/admin/projects/new",
    projectEdit: "/admin/projects/:id",
    skills: "/admin/skills",
    experience: "/admin/experience",
    education: "/admin/education",
    certificates: "/admin/certificates",
    blogs: "/admin/blogs",
    blogNew: "/admin/blogs/new",
    blogEdit: "/admin/blogs/:id",
    contact: "/admin/contact",
    contactDetail: "/admin/contact/:id",
    uploads: "/admin/uploads",
    analytics: "/admin/analytics",
    settings: "/admin/settings",
    account: "/admin/account",
  },
};

export default routes;
